fix: missing default $in_args for change_php_workers
Resolves the following:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WPCD_WORDPRESS_TABS_PHP_OPTIONS::change_php_workers(), 2 passed in /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/php-options.php on line 188 and exactly 3 expected in /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/php-options.php:977
Stack trace:
#0 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/php-options.php(188): WPCD_WORDPRESS_TABS_PHP_OPTIONS->change_php_workers()
#1 /wp-includes/class-wp-hook.php(324): WPCD_WORDPRESS_TABS_PHP_OPTIONS->tab_action()
#2 /wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/class-wordpress-app.php(2566): apply_filters()
#4 /wp-includes/class-wp-hook.php(324): WPCD_WORDPRESS_APP->ajax_app()
#5 /wp-includes/ in /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/php-options.php on line 977
```